# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
#source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'
#flipperkit_version = '0.128.2'

use_frameworks!

workspace 'Swift_SweetSugar.xcworkspace'

target 'Swift_SweetSugar' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod 'Kingfisher'
  pod 'YYText' #:modular_headers => true
  pod 'SnapKit'
  pod 'lottie-ios', '~> 3.2.3'
  pod 'SwiftyJSON'
  pod 'testDev', :path => './testDev/'
  pod 'KSCrash', '~> 2.0'
  pod 'Alamofire'

  pod 'MLeaksFinder', :configurations => ['Debug']
  pod 'FBRetainCycleDetector', :git => 'git@gitlab.corp.youdao.com:lunafork/FBRetainCycleDetector.git', :branch => 'feature/yd_dev'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug'] #必选
  pod 'Toaster'
  # Pods for Swift_SweetSugar

  #调试
#  pod 'FlipperKit', '~>' + flipperkit_version, :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitLayoutComponentKitSupport', '~>' + flipperkit_version, :configuration => 'Debug'
#  pod 'FlipperKit/SKIOSNetworkPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
#  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', '~>' + flipperkit_version, :configuration => 'Debug'
#
#  pod 'Flipper-DoubleConversion', :configuration => 'Debug'
#   pod 'Flipper-Folly', :configuration => 'Debug'
#   pod 'Flipper-Glog', :configuration => 'Debug'
#   pod 'Flipper-PeerTalk', :configuration => 'Debug'
#   pod 'CocoaLibEvent', :configuration => 'Debug'
#   pod 'boost-for-react-native', :configuration => 'Debug'
#   pod 'OpenSSL-Universal', :configuration => 'Debug'
#   pod 'CocoaAsyncSocket', :configuration => 'Debug'
#
#   pod 'ComponentKit', '~> 0.31', :configuration => 'Debug'
#
#    $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
#      'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
#      'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
#      'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
#
#    pre_install do |installer|
#      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
#      installer.pod_targets.each do |pod|
#          if $static_framework.include?(pod.name)
#            def pod.build_type;
#              Pod::BuildType.static_library
#            end
#          end
#        end
#    end
  #调试 end
  
  target 'Swift_SweetSugarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift_SweetSugarUITests' do
    # Pods for testing
  end

end

#def fix_config(config)
#  # https://github.com/CocoaPods/CocoaPods/issues/8891
#  if config.build_settings['DEVELOPMENT_TEAM'].nil?
#    config.build_settings['DEVELOPMENT_TEAM'] = 'T6H68KJ4WD'
#  end
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      #      if target.name.include? 'TransWidgetExtension'
      ##      elsif target.name.include? 'YDTExtentionService' then
      ##      elsif target.name.include? 'YDTWidget' then
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # 针对M1机型 模拟器 https://juejin.cn/post/7037037120158269448
#      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "$(inherited)"

      config.build_settings['MERGED_BINARY_TYPE'] = 'automatic'

      #      else
      #      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      #    end
      #      target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      #    config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      
      #Require Only AppExtension-Safe
      #    config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      #    fix_config(config)
    end
  end
end


