# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift_SweetSugar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  # Pods for Swift_SweetSugar

  target 'Swift_SweetSugarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift_SweetSugarUITests' do
    # Pods for testing
  end

end
